import {
  Baby,
  BookOpen,
  CalendarDays,
  Church,
  Compass,
  Gem,
  Gift,
  Globe2,
  HandHeart,
  HandHelping,
  Handshake,
  Heart,
  Lock,
  MapPin,
  Megaphone,
  MessageCircle,
  Music,
  Plane,
  ShieldCheck,
  Sparkles,
  Sprout,
  Star,
  Target,
  Users,
  UsersRound,
  type LucideIcon,
} from 'lucide-react'

const map: Record<string, LucideIcon> = {
  heart: Heart,
  users: Users,
  'users-round': UsersRound,
  book: BookOpen,
  globe: Globe2,
  church: Church,
  'hand-heart': HandHeart,
  hands: HandHelping,
  handshake: Handshake,
  sprout: Sprout,
  megaphone: Megaphone,
  music: Music,
  calendar: CalendarDays,
  'map-pin': MapPin,
  lock: Lock,
  shield: ShieldCheck,
  target: Target,
  compass: Compass,
  gem: Gem,
  sparkles: Sparkles,
  baby: Baby,
  gift: Gift,
  plane: Plane,
  message: MessageCircle,
  star: Star,
}

export const iconFor = (name?: string | null): LucideIcon => (name && map[name]) || Heart
