/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    sermons: Sermon;
    ministries: Ministry;
    missions: Mission;
    media: Media;
    testimonials: Testimonial;
    'prayer-requests': PrayerRequest;
    'visit-plans': VisitPlan;
    'event-registrations': EventRegistration;
    'newsletter-subscribers': NewsletterSubscriber;
    'page-views': PageView;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    missions: MissionsSelect<false> | MissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    'visit-plans': VisitPlansSelect<false> | VisitPlansSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  image?: (number | null) | Media;
  startsAt: string;
  timeToConfirm?: boolean | null;
  location?: string | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  registrationEnabled?: boolean | null;
  capacity?: number | null;
  /**
   * Adresse de la page. Générée automatiquement à partir du titre si vide.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez l’image pour les personnes malvoyantes (accessibilité).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  title: string;
  preacher?: string | null;
  date: string;
  series?: string | null;
  category?: string | null;
  /**
   * Affiché sur la page d’accueil (sinon, le plus récent).
   */
  featured?: boolean | null;
  thumbnail?: (number | null) | Media;
  preacherPhoto?: (number | null) | Media;
  /**
   * Si aucune miniature n’est fournie, celle de YouTube est utilisée.
   */
  youtubeUrl?: string | null;
  podcastUrl?: string | null;
  audioFile?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Adresse de la page. Générée automatiquement à partir du titre si vide.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  name: string;
  image?: (number | null) | Media;
  icon?:
    | (
        | 'baby'
        | 'book'
        | 'flower'
        | 'users'
        | 'heart-handshake'
        | 'hand-heart'
        | 'music'
        | 'globe'
        | 'video'
        | 'graduation-cap'
        | 'megaphone'
      )
    | null;
  accent?: ('blue' | 'red' | 'green' | 'purple' | 'gold') | null;
  order?: number | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  leader?: string | null;
  schedule?: string | null;
  /**
   * Adresse de la page. Générée automatiquement à partir du titre si vide.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions".
 */
export interface Mission {
  id: number;
  project: string;
  zone: string;
  description?: string | null;
  images?: (number | Media)[] | null;
  status?: ('active' | 'planned' | 'done') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  firstName: string;
  email?: string | null;
  text: string;
  photo?: (number | null) | Media;
  consent: boolean;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  request: string;
  wantsReply?: boolean | null;
  confidential?: boolean | null;
  status?: ('new' | 'praying' | 'answered' | 'archived') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-plans".
 */
export interface VisitPlan {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  visitDate?: string | null;
  people?: number | null;
  withChildren?: boolean | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  name: string;
  email: string;
  seats?: number | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  name?: string | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  day: string;
  path: string;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Administrateur : tout. Éditeur : contenus publics. Équipe pastorale : demandes de prière et visites.
   */
  role: 'admin' | 'editor' | 'pastoral';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'missions';
        value: number | Mission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null)
    | ({
        relationTo: 'visit-plans';
        value: number | VisitPlan;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  startsAt?: T;
  timeToConfirm?: T;
  location?: T;
  summary?: T;
  description?: T;
  registrationEnabled?: T;
  capacity?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  preacher?: T;
  date?: T;
  series?: T;
  category?: T;
  featured?: T;
  thumbnail?: T;
  preacherPhoto?: T;
  youtubeUrl?: T;
  podcastUrl?: T;
  audioFile?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  icon?: T;
  accent?: T;
  order?: T;
  summary?: T;
  description?: T;
  leader?: T;
  schedule?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions_select".
 */
export interface MissionsSelect<T extends boolean = true> {
  project?: T;
  zone?: T;
  description?: T;
  images?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  firstName?: T;
  email?: T;
  text?: T;
  photo?: T;
  consent?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  request?: T;
  wantsReply?: T;
  confidential?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-plans_select".
 */
export interface VisitPlansSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  visitDate?: T;
  people?: T;
  withChildren?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  email?: T;
  seats?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  day?: T;
  path?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    lines?:
      | {
          lead?: string | null;
          highlight?: string | null;
          id?: string | null;
        }[]
      | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
    video?: (number | null) | Media;
  };
  welcome?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
    cards?:
      | {
          title: string;
          text?: string | null;
          href?: string | null;
          icon?: ('church' | 'book' | 'users') | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pillars?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
    background?: (number | null) | Media;
    items?:
      | {
          title: string;
          text?: string | null;
          icon?: ('megaphone' | 'book' | 'users' | 'heart') | null;
          id?: string | null;
        }[]
      | null;
  };
  prayer?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
  };
  missions?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    zones?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    images?: (number | Media)[] | null;
  };
  finalCta?: {
    title?: string | null;
    text?: string | null;
    background?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name?: string | null;
  tagline?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  serviceDay?: string | null;
  serviceTime?: string | null;
  city?: string | null;
  address?: string | null;
  postalCode?: string | null;
  directionsUrl?: string | null;
  phone?: string | null;
  email?: string | null;
  donateUrl?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  whatsapp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        lines?:
          | T
          | {
              lead?: T;
              highlight?: T;
              id?: T;
            };
        subtitle?: T;
        image?: T;
        video?: T;
      };
  welcome?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        cards?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              icon?: T;
              image?: T;
              id?: T;
            };
      };
  pillars?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        background?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              icon?: T;
              id?: T;
            };
      };
  prayer?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
      };
  missions?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        text?: T;
        zones?:
          | T
          | {
              name?: T;
              id?: T;
            };
        images?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        text?: T;
        background?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  serviceDay?: T;
  serviceTime?: T;
  city?: T;
  address?: T;
  postalCode?: T;
  directionsUrl?: T;
  phone?: T;
  email?: T;
  donateUrl?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  tiktok?: T;
  whatsapp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}