/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    'event-registrations': EventRegistration;
    'contact-messages': ContactMessage;
    donations: Donation;
    'prayer-requests': PrayerRequest;
    'visit-plans': VisitPlan;
    ministries: Ministry;
    missions: Mission;
    sermons: Sermon;
    testimonials: Testimonial;
    announcements: Announcement;
    'email-campaigns': EmailCampaign;
    'social-posts': SocialPost;
    'newsletter-subscribers': NewsletterSubscriber;
    media: Media;
    documents: Document;
    links: Link;
    users: User;
    'page-views': PageView;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    'visit-plans': VisitPlansSelect<false> | VisitPlansSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    missions: MissionsSelect<false> | MissionsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'page-eglise': PageEglise;
    'page-decouvrir': PageDecouvrir;
    'page-ministeres': PageMinistere;
    'page-messages': PageMessage;
    'page-evenements': PageEvenement;
    'page-missions': PageMission;
    'page-priere': PagePriere;
    'page-don': PageDon;
    'page-contact': PageContact;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'page-eglise': PageEgliseSelect<false> | PageEgliseSelect<true>;
    'page-decouvrir': PageDecouvrirSelect<false> | PageDecouvrirSelect<true>;
    'page-ministeres': PageMinisteresSelect<false> | PageMinisteresSelect<true>;
    'page-messages': PageMessagesSelect<false> | PageMessagesSelect<true>;
    'page-evenements': PageEvenementsSelect<false> | PageEvenementsSelect<true>;
    'page-missions': PageMissionsSelect<false> | PageMissionsSelect<true>;
    'page-priere': PagePriereSelect<false> | PagePriereSelect<true>;
    'page-don': PageDonSelect<false> | PageDonSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  image?: (number | null) | Media;
  startsAt: string;
  endsAt?: string | null;
  timeToConfirm?: boolean | null;
  category?:
    ('louange' | 'enseignement' | 'priere' | 'conference' | 'atelier' | 'jeunesse' | 'famille' | 'rencontre') | null;
  format?: ('onsite' | 'online' | 'hybrid') | null;
  /**
   * Mis en avant en haut de la page Événements.
   */
  featured?: boolean | null;
  location?: string | null;
  streamUrl?: string | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  registrationEnabled?: boolean | null;
  capacity?: number | null;
  /**
   * Adresse de la page. Générée automatiquement à partir du titre si vide.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos, vidéos et fichiers publics du site. Pour les documents internes, utilisez « Documents ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez l’image pour les personnes malvoyantes (accessibilité).
   */
  alt: string;
  folder?:
    | (
        | 'ministeres'
        | 'missions'
        | 'evenements'
        | 'communications'
        | 'formations'
        | 'administration'
        | 'modeles'
        | 'site'
        | 'autres'
      )
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  name: string;
  email: string;
  seats?: number | null;
  consent: boolean;
  status?: ('confirmed' | 'pending' | 'cancelled') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  newsletter?: boolean | null;
  status?: ('new' | 'answered' | 'archived') | null;
  important?: boolean | null;
  readAt?: string | null;
  answeredAt?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  date: string;
  amount: number;
  donorName: string;
  email?: string | null;
  category: 'general' | 'tithe' | 'missions' | 'projects' | 'building' | 'social' | 'youth' | 'other';
  method: 'card' | 'interac' | 'bank' | 'cheque' | 'cash' | 'online';
  status?: ('confirmed' | 'pending' | 'refunded') | null;
  recurring?: boolean | null;
  receiptSent?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  request: string;
  wantsReply?: boolean | null;
  confidential?: boolean | null;
  status?: ('new' | 'praying' | 'answered' | 'archived') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-plans".
 */
export interface VisitPlan {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  visitDate?: string | null;
  people?: number | null;
  withChildren?: boolean | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  name: string;
  image?: (number | null) | Media;
  icon?:
    | (
        | 'baby'
        | 'book'
        | 'flower'
        | 'users'
        | 'heart-handshake'
        | 'hand-heart'
        | 'music'
        | 'globe'
        | 'video'
        | 'graduation-cap'
        | 'megaphone'
      )
    | null;
  accent?: ('blue' | 'red' | 'green' | 'purple' | 'gold') | null;
  order?: number | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  leader?: string | null;
  schedule?: string | null;
  /**
   * Adresse de la page. Générée automatiquement à partir du titre si vide.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions".
 */
export interface Mission {
  id: number;
  project: string;
  zone: string;
  scope?: ('quebec' | 'canada' | 'international') | null;
  startDate?: string | null;
  endDate?: string | null;
  progress?: number | null;
  leader?: string | null;
  ministry?: (number | null) | Ministry;
  description?: string | null;
  images?: (number | Media)[] | null;
  status?: ('active' | 'planned' | 'done') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  title: string;
  preacher?: string | null;
  date: string;
  series?: string | null;
  category?: string | null;
  /**
   * Affiché sur la page d’accueil (sinon, le plus récent).
   */
  featured?: boolean | null;
  thumbnail?: (number | null) | Media;
  preacherPhoto?: (number | null) | Media;
  /**
   * Si aucune miniature n’est fournie, celle de YouTube est utilisée.
   */
  youtubeUrl?: string | null;
  podcastUrl?: string | null;
  audioFile?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Adresse de la page. Générée automatiquement à partir du titre si vide.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  firstName: string;
  email?: string | null;
  text: string;
  photo?: (number | null) | Media;
  consent: boolean;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  summary: string;
  image?: (number | null) | Media;
  link?: string | null;
  linkLabel?: string | null;
  category?: ('evenement' | 'priere' | 'formation' | 'missions' | 'enseignement' | 'familles' | 'eglise') | null;
  /**
   * Une annonce publiée avec une date future est « planifiée ».
   */
  status?: ('draft' | 'pending' | 'published' | 'archived') | null;
  publishAt: string;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: number;
  subject: string;
  preheader?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  audience: 'newsletter' | 'event' | 'contacts';
  event?: (number | null) | Event;
  status?: ('draft' | 'scheduled' | 'sent') | null;
  scheduledAt?: string | null;
  sentAt?: string | null;
  recipients?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  title: string;
  caption?: string | null;
  image?: (number | null) | Media;
  platforms: ('facebook' | 'instagram' | 'youtube' | 'tiktok' | 'whatsapp')[];
  format?: ('photo' | 'video' | 'carousel' | 'story' | 'live' | 'link') | null;
  link?: string | null;
  status?: ('draft' | 'scheduled' | 'published') | null;
  scheduledAt?: string | null;
  postUrl?: string | null;
  reach?: number | null;
  likes?: number | null;
  comments?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  name?: string | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  description?: string | null;
  folder?:
    | (
        | 'ministeres'
        | 'missions'
        | 'evenements'
        | 'communications'
        | 'formations'
        | 'administration'
        | 'modeles'
        | 'site'
        | 'autres'
      )
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  title: string;
  url: string;
  description?: string | null;
  folder?:
    | (
        | 'ministeres'
        | 'missions'
        | 'evenements'
        | 'communications'
        | 'formations'
        | 'administration'
        | 'modeles'
        | 'site'
        | 'autres'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  title?: string | null;
  phone?: string | null;
  /**
   * Décocher pour suspendre l’accès sans supprimer le compte.
   */
  active?: boolean | null;
  lastLoginAt?: string | null;
  /**
   * Administrateur : tout. Éditeur : contenus publics. Équipe pastorale : demandes de prière et visites.
   */
  role: 'admin' | 'editor' | 'pastoral';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  day: string;
  path: string;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null)
    | ({
        relationTo: 'visit-plans';
        value: number | VisitPlan;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'missions';
        value: number | Mission;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: number | EmailCampaign;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  startsAt?: T;
  endsAt?: T;
  timeToConfirm?: T;
  category?: T;
  format?: T;
  featured?: T;
  location?: T;
  streamUrl?: T;
  summary?: T;
  description?: T;
  registrationEnabled?: T;
  capacity?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  email?: T;
  seats?: T;
  consent?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  newsletter?: T;
  status?: T;
  important?: T;
  readAt?: T;
  answeredAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  date?: T;
  amount?: T;
  donorName?: T;
  email?: T;
  category?: T;
  method?: T;
  status?: T;
  recurring?: T;
  receiptSent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  request?: T;
  wantsReply?: T;
  confidential?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-plans_select".
 */
export interface VisitPlansSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  visitDate?: T;
  people?: T;
  withChildren?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  icon?: T;
  accent?: T;
  order?: T;
  summary?: T;
  description?: T;
  leader?: T;
  schedule?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions_select".
 */
export interface MissionsSelect<T extends boolean = true> {
  project?: T;
  zone?: T;
  scope?: T;
  startDate?: T;
  endDate?: T;
  progress?: T;
  leader?: T;
  ministry?: T;
  description?: T;
  images?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  preacher?: T;
  date?: T;
  series?: T;
  category?: T;
  featured?: T;
  thumbnail?: T;
  preacherPhoto?: T;
  youtubeUrl?: T;
  podcastUrl?: T;
  audioFile?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  firstName?: T;
  email?: T;
  text?: T;
  photo?: T;
  consent?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  image?: T;
  link?: T;
  linkLabel?: T;
  category?: T;
  status?: T;
  publishAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  subject?: T;
  preheader?: T;
  body?: T;
  audience?: T;
  event?: T;
  status?: T;
  scheduledAt?: T;
  sentAt?: T;
  recipients?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  image?: T;
  platforms?: T;
  format?: T;
  link?: T;
  status?: T;
  scheduledAt?: T;
  postUrl?: T;
  reach?: T;
  likes?: T;
  comments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  description?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  phone?: T;
  active?: T;
  lastLoginAt?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  day?: T;
  path?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Chaque onglet correspond à une section de la page d’accueil. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    lines?:
      | {
          lead?: string | null;
          highlight?: string | null;
          id?: string | null;
        }[]
      | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
    video?: (number | null) | Media;
  };
  welcome?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
    cards?:
      | {
          title: string;
          text?: string | null;
          href?: string | null;
          icon?: ('church' | 'book' | 'users') | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pillars?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
    background?: (number | null) | Media;
    items?:
      | {
          title: string;
          text?: string | null;
          icon?: ('megaphone' | 'book' | 'users' | 'heart') | null;
          id?: string | null;
        }[]
      | null;
  };
  prayer?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
  };
  missions?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    zones?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    images?: (number | Media)[] | null;
  };
  finalCta?: {
    title?: string | null;
    text?: string | null;
    background?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-eglise".
 */
export interface PageEglise {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  features?: {
    items?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  welcome?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    image?: (number | null) | Media;
  };
  services?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Le jour, l’heure et l’adresse se modifient dans Paramètres › Informations de l’église.
     */
    serviceLabel?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
  };
  groups?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    cards?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  membership?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    image?: (number | null) | Media;
    steps?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    questions?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-decouvrir".
 */
export interface PageDecouvrir {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  about?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
    highlights?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          id?: string | null;
        }[]
      | null;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  pillars?: {
    items?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  story?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    timeline?:
      | {
          label: string;
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  vision?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  team?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    leaders?:
      | {
          name: string;
          role: string;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  faith?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    image?: (number | null) | Media;
  };
  network?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
  };
  cta?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-ministeres".
 */
export interface PageMinistere {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  features?: {
    items?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  list?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
  };
  serve?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    image?: (number | null) | Media;
    steps?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  spotlight?: {
    eyebrow?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    /**
     * Doit correspondre au nom d’un ministère.
     */
    ministryName?: string | null;
    activitiesTitle?: string | null;
  };
  cta?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-messages".
 */
export interface PageMessage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  featured?: {
    eyebrow?: string | null;
  };
  library?: {
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
  };
  podcast?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    spotifyUrl?: string | null;
    applePodcastsUrl?: string | null;
    youtubeChannelUrl?: string | null;
  };
  newsletter?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-evenements".
 */
export interface PageEvenement {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  features?: {
    items?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  featured?: {
    eyebrow?: string | null;
  };
  list?: {
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
  };
  newsletter?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-missions".
 */
export interface PageMission {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  features?: {
    items?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  vision?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  fields?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
  };
  presence?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
  };
  involve?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    ways?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          link?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
  };
  cta?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-priere".
 */
export interface PagePriere {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  features?: {
    items?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  request?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
    formTitle?: string | null;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  others?: {
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
  };
  process?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    steps?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
  };
  cta?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-don".
 */
export interface PageDon {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
    quoteText?: string | null;
    quoteSource?: string | null;
  };
  features?: {
    items?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ways?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    onlineText?: string | null;
    interacEmail?: string | null;
    interacNote?: string | null;
    mailingAddress?: string | null;
    inPersonNote?: string | null;
  };
  impact?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
    uses?:
      | {
          icon:
            | 'heart'
            | 'users'
            | 'users-round'
            | 'book'
            | 'globe'
            | 'church'
            | 'hand-heart'
            | 'hands'
            | 'handshake'
            | 'sprout'
            | 'megaphone'
            | 'music'
            | 'calendar'
            | 'map-pin'
            | 'lock'
            | 'shield'
            | 'target'
            | 'compass'
            | 'gem'
            | 'sparkles'
            | 'baby'
            | 'gift'
            | 'plane'
            | 'message'
            | 'star';
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  trust?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    charityNumber?: string | null;
    /**
     * Cocher seulement si MKMI Québec est un organisme de bienfaisance enregistré.
     */
    taxReceipts?: boolean | null;
  };
  cta?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chaque onglet correspond à une section de la page, dans l’ordre d’affichage. L’aperçu à droite se met à jour pendant que vous écrivez ; cliquez sur « Publier les modifications » pour mettre en ligne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  info?: {
    officeHours?: string | null;
  };
  visit?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    button?: string | null;
    image?: (number | null) | Media;
  };
  form?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
  };
  others?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
  };
  faq?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    questions?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    eyebrow?: string | null;
    /**
     * Mettez entre *astérisques* les mots à afficher en or. Un retour à la ligne crée une nouvelle ligne.
     */
    title?: string | null;
    text?: string | null;
    /**
     * Texte du bouton.
     */
    primary?: string | null;
    /**
     * Texte du bouton.
     */
    secondary?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name?: string | null;
  tagline?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  serviceDay?: string | null;
  serviceTime?: string | null;
  city?: string | null;
  address?: string | null;
  postalCode?: string | null;
  directionsUrl?: string | null;
  phone?: string | null;
  email?: string | null;
  donateUrl?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  whatsapp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        lines?:
          | T
          | {
              lead?: T;
              highlight?: T;
              id?: T;
            };
        subtitle?: T;
        image?: T;
        video?: T;
      };
  welcome?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        cards?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              icon?: T;
              image?: T;
              id?: T;
            };
      };
  pillars?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        background?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              icon?: T;
              id?: T;
            };
      };
  prayer?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
      };
  missions?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        text?: T;
        zones?:
          | T
          | {
              name?: T;
              id?: T;
            };
        images?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        text?: T;
        background?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-eglise_select".
 */
export interface PageEgliseSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  features?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  welcome?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
        image?: T;
      };
  services?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        serviceLabel?: T;
        primary?: T;
        secondary?: T;
      };
  groups?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              image?: T;
              id?: T;
            };
      };
  membership?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
        image?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-decouvrir_select".
 */
export interface PageDecouvrirSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
        highlights?:
          | T
          | {
              icon?: T;
              title?: T;
              id?: T;
            };
        quoteText?: T;
        quoteSource?: T;
      };
  pillars?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        timeline?:
          | T
          | {
              label?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  vision?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  team?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        leaders?:
          | T
          | {
              name?: T;
              role?: T;
              photo?: T;
              id?: T;
            };
      };
  faith?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
        image?: T;
      };
  network?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-ministeres_select".
 */
export interface PageMinisteresSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  features?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  list?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  serve?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
        image?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              id?: T;
            };
      };
  spotlight?:
    | T
    | {
        eyebrow?: T;
        button?: T;
        ministryName?: T;
        activitiesTitle?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-messages_select".
 */
export interface PageMessagesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  featured?:
    | T
    | {
        eyebrow?: T;
      };
  library?:
    | T
    | {
        title?: T;
      };
  podcast?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        spotifyUrl?: T;
        applePodcastsUrl?: T;
        youtubeChannelUrl?: T;
      };
  newsletter?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-evenements_select".
 */
export interface PageEvenementsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  features?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  featured?:
    | T
    | {
        eyebrow?: T;
      };
  list?:
    | T
    | {
        title?: T;
      };
  newsletter?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-missions_select".
 */
export interface PageMissionsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  features?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  vision?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  fields?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  presence?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  involve?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        ways?:
          | T
          | {
              icon?: T;
              title?: T;
              link?: T;
              text?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-priere_select".
 */
export interface PagePriereSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  features?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  request?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
        formTitle?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  others?:
    | T
    | {
        title?: T;
      };
  process?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-don_select".
 */
export interface PageDonSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
        quoteText?: T;
        quoteSource?: T;
      };
  features?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  ways?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        onlineText?: T;
        interacEmail?: T;
        interacNote?: T;
        mailingAddress?: T;
        inPersonNote?: T;
      };
  impact?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
        uses?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  trust?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        charityNumber?: T;
        taxReceipts?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  info?:
    | T
    | {
        officeHours?: T;
      };
  visit?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        button?: T;
        image?: T;
      };
  form?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  others?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        primary?: T;
        secondary?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  serviceDay?: T;
  serviceTime?: T;
  city?: T;
  address?: T;
  postalCode?: T;
  directionsUrl?: T;
  phone?: T;
  email?: T;
  donateUrl?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  tiktok?: T;
  whatsapp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}